#!/usr/bin/env python3
"""
Doom-Inspired Fixed-Point Trigonometric Lookup Table Generator
Generates sine LUT with 8192 entries for ESP32-S3 (16.16 fixed-point format)

Reference: id-Software/DOOM linuxdoom-1.10/tables.c
Author: ClaudeCode (Doom→SE(3) λ-Estimation Service)
Version: 1.0
"""

import math
import os

# Fixed-point configuration (matching Doom's m_fixed.h)
FRACBITS = 16
FRACUNIT = 1 << FRACBITS  # 65,536

# Angle table configuration (matching Doom's tables.h)
ANGLE_BITS = 13
NUM_FINE_ANGLES = 1 << ANGLE_BITS  # 8192 entries


def float_to_fixed(f: float) -> int:
    """
    Convert floating-point value to 16.16 fixed-point integer.

    Args:
        f: Floating-point value in range [-32768, 32767]

    Returns:
        32-bit signed integer in fixed-point format
    """
    return int(round(f * FRACUNIT))


def generate_trig_tables_header(output_path: str) -> None:
    """
    Generate trig_tables.h with sine lookup table DATA (for .c file).

    The cosine table is accessed via pointer offset:
        finecosine = &finesine[NUM_FINE_ANGLES / 4]

    Args:
        output_path: Path to output header file (will be included in trig_tables.c)
    """
    with open(output_path, 'w') as f:
        # Header comment
        f.write('/* Generated by tools/generate_trig_lut.py - DO NOT EDIT MANUALLY */\n')
        f.write('/* This file contains the LUT data and should be included in trig_tables.c */\n')
        f.write('#ifndef TRIG_TABLES_DATA_H\n')
        f.write('#define TRIG_TABLES_DATA_H\n\n')

        # Sine table data (no static - will have external linkage when included in .c)
        f.write(f'/* Sine lookup table: 8192 entries, ~0.044° resolution */\n')
        f.write(f'const fixed_t finesine[NUM_FINE_ANGLES] = {{\n')

        # Generate sine values
        for i in range(NUM_FINE_ANGLES):
            # Angle in radians: i maps to [0, 2π)
            angle_rad = (i / NUM_FINE_ANGLES) * 2.0 * math.pi
            sin_val = math.sin(angle_rad)
            fixed_sin = float_to_fixed(sin_val)

            # Format: 8 values per line with comments every line
            if i % 8 == 0:
                f.write('    ')

            f.write(f'{fixed_sin:7d}')

            if i < NUM_FINE_ANGLES - 1:
                f.write(',')

            # Line break and comment every 8 values
            if i % 8 == 7:
                angle_deg = (i / NUM_FINE_ANGLES) * 360.0
                f.write(f'  /* {i-7:4d}-{i:4d}: {angle_deg-360.0/NUM_FINE_ANGLES*7:.2f}° - {angle_deg:.2f}° */\n')
            elif i == NUM_FINE_ANGLES - 1:
                f.write('\n')

        f.write('};\n\n')

        # Cosine pointer (Doom optimization: point into sine table at +90°)
        f.write('/* Cosine via pointer offset (cos(x) = sin(x + 90°)) */\n')
        f.write('const fixed_t* const finecosine = &finesine[NUM_FINE_ANGLES / 4];\n\n')

        f.write('#endif /* TRIG_TABLES_DATA_H */\n')


def generate_verification_data(output_path: str) -> None:
    """
    Generate verification data for testing LUT accuracy.

    Args:
        output_path: Path to output verification file
    """
    with open(output_path, 'w') as f:
        f.write('# Trigonometric LUT Verification Data\n')
        f.write(f'# Generated for {NUM_FINE_ANGLES} entries\n\n')

        # Test critical angles
        test_angles = [0, 30, 45, 60, 90, 120, 135, 150, 180, 210, 225, 240, 270, 300, 315, 330]

        f.write('angle_deg,index,sin_fixed,sin_float,cos_fixed,cos_float,error_sin,error_cos\n')

        for angle_deg in test_angles:
            angle_rad = math.radians(angle_deg)

            # Calculate index for this angle
            index = int((angle_deg / 360.0) * NUM_FINE_ANGLES) & (NUM_FINE_ANGLES - 1)

            # True values
            sin_float = math.sin(angle_rad)
            cos_float = math.cos(angle_rad)

            # Fixed-point values
            sin_fixed = float_to_fixed(sin_float)
            cos_index = (index + NUM_FINE_ANGLES // 4) & (NUM_FINE_ANGLES - 1)
            angle_rad_cos = (cos_index / NUM_FINE_ANGLES) * 2.0 * math.pi
            cos_fixed = float_to_fixed(math.sin(angle_rad_cos))

            # Errors
            error_sin = abs(sin_fixed / FRACUNIT - sin_float)
            error_cos = abs(cos_fixed / FRACUNIT - cos_float)

            f.write(f'{angle_deg},{index},{sin_fixed},{sin_float:.10f},')
            f.write(f'{cos_fixed},{cos_float:.10f},{error_sin:.10e},{error_cos:.10e}\n')


def main():
    """Generate all trigonometric lookup tables and verification data."""
    # Determine paths
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    embedded_dir = os.path.join(project_root, 'embedded')

    # Create embedded directory if it doesn't exist
    os.makedirs(embedded_dir, exist_ok=True)

    # Generate header file
    header_path = os.path.join(embedded_dir, 'trig_tables.h')
    print(f'Generating {header_path}...')
    generate_trig_tables_header(header_path)

    # Generate verification data
    verify_path = os.path.join(project_root, 'tests', 'trig_lut_verification.csv')
    os.makedirs(os.path.dirname(verify_path), exist_ok=True)
    print(f'Generating {verify_path}...')
    generate_verification_data(verify_path)

    # Print summary
    print(f'\n✓ Generated trigonometric lookup tables:')
    print(f'  - {NUM_FINE_ANGLES} sine entries (~0.044° resolution)')
    print(f'  - {FRACBITS}.{FRACBITS} fixed-point format (range: ±1.0)')
    print(f'  - Cosine via pointer offset (+{NUM_FINE_ANGLES // 4} entries)')
    print(f'  - Memory: {NUM_FINE_ANGLES * 4} bytes ({NUM_FINE_ANGLES * 4 / 1024:.1f} KB)')
    print(f'\n✓ Verification data: {verify_path}')
    print(f'\nNext steps:')
    print(f'  1. Verify accuracy: python tools/verify_trig_lut.py')
    print(f'  2. Implement se3_math.c with FixedMul/FixedDiv')
    print(f'  3. Implement trig_tables.c with Sin_from_LUT/Cos_from_LUT')


if __name__ == '__main__':
    main()
